create_vine:
    path:     '/vines'
    defaults:
        _controller: AppBundle:Vine:createVine
    methods: [POST]

update_vine:
    path:     '/vines/{id}'
    defaults:
        _controller: AppBundle:Vine:updateVine
    methods: [PUT]

post_winery:
    path:     '/wineries'
    defaults:
        _controller: AppBundle:Winery:createWinery
    methods: [POST]

post_wine:
    path:     '/wines'
    defaults:
        _controller: AppBundle:Wine:createWine
    methods: [POST]
