create_vine:
    path:     '/vine'
    defaults:
        _controller: AppBundle:Vine:createVine
    methods: [POST]

update_vine:
    path:     '/vine/{id}'
    defaults:
        _controller: AppBundle:Vine:updateVine
    methods: [PUT]

post_winery:
    path:     '/winery'
    defaults:
        _controller: AppBundle:Winery:createWinery
    methods: [POST]

post_wine:
    path:     '/wine'
    defaults:
        _controller: AppBundle:Wine:createWine
    methods: [POST]
