create_vine:
    path:     '/vines'
    defaults:
        _controller: AppBundle:Vine:createVine
    methods: [POST]

update_vine:
    path:     '/vines/{id}'
    defaults:
        _controller: AppBundle:Vine:updateVine
    methods: [PUT]

get_vine:
    path:     '/vines/{id}'
    defaults:
        _controller: AppBundle:Vine:getVine
    methods: [GET]

get_vines:
    path:     '/vines'
    defaults:
        _controller: AppBundle:Vine:getVines
    methods: [GET]

post_winery:
    path:     '/wineries'
    defaults:
        _controller: AppBundle:Winery:createWinery
    methods: [POST]

update_winery:
    path:     '/wineries/{id}'
    defaults:
        _controller: AppBundle:Winery:updateWinery
    methods: [PUT]

get_winery:
    path:     '/wineries/{id}'
    defaults:
        _controller: AppBundle:Winery:getWinery
    methods: [GET]

get_wineries:
    path:     '/wineries'
    defaults:
        _controller: AppBundle:Winery:getWineries
    methods: [GET]

post_wine:
    path:     '/wines'
    defaults:
        _controller: AppBundle:Wine:createWine
    methods: [POST]
