post_vine:
    path:     '/vine'
    defaults:
        _controller: AppBundle:Vine:createVine
    methods: [POST]

post_winery:
    path:     '/winery'
    defaults:
        _controller: AppBundle:Winery:createWinery
    methods: [POST]

post_wine:
    path:     '/wine'
    defaults:
        _controller: AppBundle:Wine:createWine
    methods: [POST]
