# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.repository.vine:
        class: Doctrine\ORM\EntityRepository
        factory:
          - "@doctrine.orm.entity_manager"
          - getRepository
        arguments:
          - AppBundle\Entity\Vine

    app.repository.winery:
        class: Doctrine\ORM\EntityRepository
        factory:
          - "@doctrine.orm.entity_manager"
          - getRepository
        arguments:
          - AppBundle\Entity\Winery

    app.repository.wine:
        class: Doctrine\ORM\EntityRepository
        factory:
          - "@doctrine.orm.entity_manager"
          - getRepository
        arguments:
          - AppBundle\Entity\Wine

    app.validator.vine_exists_validator:
        class: AppBundle\Validator\Constraints\VineExistsValidator
        arguments:
          - '@app.repository.vine'
        tags:
            - { name: validator.constraint_validator, alias: vine_exists_validator }

    app.validator.winery_exists_validator:
        class: AppBundle\Validator\Constraints\WineryExistsValidator
        arguments:
          - '@app.repository.winery'
        tags:
            - { name: validator.constraint_validator, alias: winery_exists_validator }

    app.use_case.create_vine:
        class: AppBundle\Usecase\CreateVine
        arguments:
          - '@validator'
          - "@doctrine.orm.entity_manager"

    app.use_case.update_vine:
        class: AppBundle\Usecase\UpdateVine
        arguments:
          - '@validator'
          - '@app.repository.vine'
          - "@doctrine.orm.entity_manager"

    app.use_case.get_vine:
        class: AppBundle\Usecase\GetVine
        arguments:
          - '@app.repository.vine'

    app.use_case.get_vines:
        class: AppBundle\Usecase\GetVines
        arguments:
          - '@app.repository.vine'

    app.use_case.create_winery:
        class: AppBundle\Usecase\CreateWinery
        arguments:
          - '@validator'
          - "@doctrine.orm.entity_manager"

    app.use_case.update_winery:
        class: AppBundle\Usecase\UpdateWinery
        arguments:
          - '@validator'
          - '@app.repository.winery'
          - "@doctrine.orm.entity_manager"

    app.use_case.get_winery:
        class: AppBundle\Usecase\GetWinery
        arguments:
          - '@app.repository.winery'

    app.use_case.get_wineries:
        class: AppBundle\Usecase\GetWineries
        arguments:
          - '@app.repository.winery'

    app.use_case.create_wine:
        class: AppBundle\Usecase\CreateWine
        arguments:
          - '@validator'
          - '@app.repository.winery'
          - '@app.repository.vine'
          - "@doctrine.orm.entity_manager"
