AppBundle\Entity\Rate:
    type: entity
    table: rate
    repositoryClass: AppBundle\Entity\RateRepository
    indexes:
        rate_id_idx:
            columns:
                - id
        wine_id_idx:
            columns:
                - wine_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        rate:
            type: integer
            nullable: false
            options:
                unsigned: false
    manyToOne:
        wine:
            targetEntity: AppBundle\Entity\Wine
            joinColumn:
                name: wine_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE
