AppBundle\Entity\Vine:
    type: entity
    table: vine
    repositoryClass: AppBundle\Entity\VineRepository
    indexes:
        vine_id_idx:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        grapes:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
