AppBundle\Entity\Winery:
    type: entity
    table: winery
    repositoryClass: AppBundle\Entity\WineryRepository
    indexes:
        winery_id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        city:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        region:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        country:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
