AppBundle\Entity\Wine:
    type: entity
    table: wine
    repositoryClass: AppBundle\Entity\WineRepository
    indexes:
        wine_id_idx:
            columns:
                - id
        winery_id_idx:
            columns:
                - winery_id
        vine_id_idx:
            columns:
                - vine_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        price:
            type: integer
            nullable: false
        year:
            type: string
            nullable: false
    manyToOne:
        winery:
            targetEntity: AppBundle\Entity\Winery
            joinColumn:
                name: winery_id
                referencedColumnName: id
                nullable: false
        vine:
            targetEntity: AppBundle\Entity\Vine
            joinColumn:
                name: vine_id
                referencedColumnName: id
                nullable: false
    oneToMany:
        rates:
            targetEntity: Rate
            mappedBy: wine
            cascade: ["remove"]
