<?php

namespace AppBundle\Entity;

/**
 * VineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VineRepository extends \Doctrine\ORM\EntityRepository
{
}
