<?php

namespace AppBundle\Entity;

/**
 * WineryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WineryRepository extends \Doctrine\ORM\EntityRepository
{
}
