AppBundle\DTO\VineDTO:
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 20
        grapes:
            - NotBlank: ~
            - Length:
                max: 20
