AppBundle\DTO\WineryDTO:
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 60
        city:
            - NotBlank: ~
            - Length:
                max: 30
        region:
            - NotBlank: ~
            - Length:
                max: 30
        country:
            - NotBlank: ~
            - Length:
                max: 40
