AppBundle\DTO\WineDTO:
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 60
        year:
            - NotBlank: ~
            - Regex:
                pattern: '/^([0-9]{4})?$/'
                match:   true
        price:
            - NotBlank: ~
            - Regex:
                pattern: '/^\d+$/'
                match:   true
        wineryId:
            - NotNull: ~
            - AppBundle\Validator\Constraints\WineryExists: ~
        vineId:
            - NotNull: ~
            - AppBundle\Validator\Constraints\VineExists: ~
